export enum NotificationType {
    EMAIL_SIGN_UP_CONFIRMATION,
    EMAIL_VOUCHER_CONFIRMATION,
    EMAIL_SEASON_CARD_CONFIRMATION,
    EMAIL_BASIC_CARD_CONFIRMATION,
    EMAIL_OLD_CARD_CONFIRMATION,
    EMAIL_VOUCHER_CARD_CONFIRMATION,
    EMAIL_CHANGE_PASSWORD_CONFIRMATION,
    EMAIL_SIGN_UP_VALIDATION,
    EMAIL_CHANGE_EMAIL_VALIDATION,
    EMAIL_RESELLER_CREATE,
    EMAIL_RESET_PASSWORD_IDENTIFICATION,
    EMAIL_RESELLER_PASSWORD_IDENTIFICATION
}